name: xarray-docs
channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.6
  - numpy>=1.14
  - numpydoc
  - matplotlib>=2.1.2
  - sphinx>=1.5
  - sphinx-gallery
  - ipython>=6.2.1
  - gcc
