name: Test

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  test:
    name: Test

    strategy:
      matrix:
        python-version: ['3.8', '3.x']
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
      fail-fast: false

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - uses: ./.github/actions/setup-build-env

    - name: Install py3nj
      run: |
        pip install .

    - name: Install test dependencies
      run: |
        pip install pytest

    - name: Run test suite
      run: |
        pytest

    - name: Build wheels
      if: matrix.python-version == '3.x'  # only run once per OS
      uses: pypa/cibuildwheel@v2.15.0
      env:
        CIBW_SKIP: cp312-*
