name: Test

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  test:
    name: Test

    strategy:
      matrix:
        python-version: ['3.8', '3.x']
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
      fail-fast: false

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - uses: awvwgk/setup-fortran@v1

    - name: Install build dependencies
      run: |
        pip install --upgrade pip

    - name: Install build dependencies (Linux)
      if: startsWith(matrix.os, 'ubuntu')
      run: |
        sudo apt-get install -y ninja-build

    - name: Install build dependencies (Mac OS)
      if: startsWith(matrix.os, 'macos')
      run: |
        brew install ninja

    - name: Install build dependencies (Windows)
      if: startsWith(matrix.os, 'windows')
      run: |
        choco install ninja

    - name: Prepare MSVC (Windows)
      if: startsWith(matrix.os, 'windows')
      uses: bus1/cabuild/action/msdevshell@v1
      with:
        architecture: x64

    - name: Install py3nj
      run: |
        pip install .

    - name: Install test dependencies
      run: |
        pip install pytest

    - name: Run test suite
      run: |
        pytest


